import {useMemo,useState} from "react";import {motion} from "framer-motion";import {api} from "./api";
const labels={exact_or_near_exact:"Exact / near-exact",likely_paraphrase:"Likely paraphrase",weak_similarity:"Weak similarity",none:"No notable overlap"};
function Score({label,value,tone,note}){const v=Math.max(0,Math.min(100,Number(value||0)));return <div className={`score ${tone}`}><span>{label}</span><strong>{v.toFixed(1)}%</strong><div className="track"><div className="fill" style={{width:`${v}%`}}/></div>{note&&<p>{note}</p>}</div>}
function Diagnostics({d}){if(!d)return null;const rows=[["API connected",d.api_connected?"Yes":"No"],["Queries attempted",d.queries_attempted],["Queries successful",d.queries_successful],["Candidate URLs",d.candidate_urls],["HTML pages fetched",d.pages_fetched],["PDFs fetched",d.pdfs_fetched],["Pages failed",d.pages_failed],["Matched sources",d.matched_sources]];return <div className="diag-grid">{rows.map(([k,v])=><div className="diag" key={k}><span>{k}</span><strong>{String(v)}</strong></div>)}</div>}
function Sources({rows=[]}){if(!rows.length)return <div className="empty">No attributable matching sources were found.</div>;return <div className="sources">{rows.map(s=><div className="source" key={s.id}><div><strong>{s.title}</strong><a href={s.source?.startsWith("http")?s.source:undefined} target="_blank" rel="noreferrer">{s.source}</a><small>{s.matched_sentence_count} sentence(s) · {s.exact_sentence_count} exact · {s.paraphrase_sentence_count} paraphrase · {s.fetch_kind}</small></div><div className="source-right"><b>{s.contribution}%</b><span>match contribution</span><small>Discovery {s.discovery_confidence}</small></div></div>)}</div>}
function DocumentView({rows=[]}){return <div className="doc">{rows.map(r=><span key={r.index} className={`sent ${r.classification} ${r.quoted?"quoted":""}`} title={`${labels[r.classification]} · ${r.similarity}%${r.source_title?` · ${r.source_title}`:""}`}>{r.text} </span>)}</div>}
export default function App(){
const[text,setText]=useState("");const[file,setFile]=useState(null);const[includeWeb,setIncludeWeb]=useState(true);const[excludeReferences,setExcludeReferences]=useState(true);const[result,setResult]=useState(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[tab,setTab]=useState("overview");
const can=useMemo(()=>(file||text.trim().split(/\s+/).length>=20)&&!busy,[file,text,busy]);
async function analyze(){try{setBusy(true);setError("");setResult(null);setTab("overview");let res;if(file){const f=new FormData();f.append("file",file);f.append("include_web",String(includeWeb));f.append("exclude_references",String(excludeReferences));res=await api.post("/api/analyze-file",f)}else{res=await api.post("/api/analyze",{text,include_web:includeWeb,exclude_references:excludeReferences})}setResult(res.data)}catch(e){setError(e.response?.data?.detail||e.message||"Analysis failed.")}finally{setBusy(false)}}
return <div className="app"><header><div className="brand"><div className="mark">IL</div><div><strong>IntegrityLens Pro <sup>v2.2</sup></strong><span>Evidence-first plagiarism & AI-writing analysis</span></div></div><div className="badge">Sliding-window Match Engine • PDF Sources • Diagnostics</div></header>
<main className="shell"><motion.section className="hero" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div><span className="eyebrow">IntegrityLens Pro v2.2</span><h1>Stronger source matching after discovery.</h1><p>v2.2 preserves search snippets, extracts public PDFs, uses sliding source windows, and combines TF-IDF, sequence similarity, and 4/5/6-gram overlap.</p></div><div className="proof"><div><b>Snippet + page evidence</b><span>Search evidence is never discarded</span></div><div><b>PDF source retrieval</b><span>Public academic PDFs are parsed</span></div><div><b>Sliding-window matching</b><span>Detects partial and cross-sentence reuse</span></div></div></motion.section>
<section className="workspace"><div className="panel input"><span className="eyebrow dark">Document</span><h2>Analyze text</h2><p className="muted">Paste text or upload TXT, MD, DOCX, or PDF.</p><textarea value={text} placeholder="Paste the document here..." onChange={e=>{setText(e.target.value);setFile(null)}}/><div className="controls"><label className="upload"><input type="file" accept=".txt,.md,.docx,.pdf" onChange={e=>{setFile(e.target.files?.[0]||null);if(e.target.files?.[0])setText("")}}/><span>{file?`Selected: ${file.name}`:"Upload document"}</span></label><label className="check"><input type="checkbox" checked={includeWeb} onChange={e=>setIncludeWeb(e.target.checked)}/><span>Search live web</span></label><label className="check"><input type="checkbox" checked={excludeReferences} onChange={e=>setExcludeReferences(e.target.checked)}/><span>Exclude bibliography</span></label><button disabled={!can} onClick={analyze}>{busy?"Searching, fetching, matching...":"Run IntegrityLens v2.2"}</button></div>{error&&<div className="error">{error}</div>}</div>
<div className="panel result">{!result?<div className="placeholder"><div className="orb">2.2</div><h3>Match-quality report will appear here</h3><p>Search diagnostics, source retrieval quality, exact overlap, likely paraphrase, and AI-writing signals are separated.</p></div>:<motion.div initial={{opacity:0}} animate={{opacity:1}}><div className="reporthead"><div><span className="eyebrow dark">Integrity report</span><h2>{result.summary.word_count.toLocaleString()} words submitted</h2><p className="tiny">{result.summary.analyzed_word_count.toLocaleString()} analyzed · {result.summary.excluded_reference_words.toLocaleString()} reference words excluded</p></div><button className="print" onClick={()=>window.print()}>Print / PDF</button></div>
<div className="scores"><Score label="Potential issue similarity" value={result.summary.potential_issue_similarity} tone="orange" note="Matched text excluding detected quotations."/><Score label="All matched text" value={result.summary.matched_text_coverage} tone="red"/><Score label="Exact / near-exact" value={result.summary.exact_near_exact_coverage} tone="blue"/><Score label="Likely paraphrase" value={result.summary.paraphrase_coverage} tone="purple"/><Score label="Detected quotations" value={result.summary.quoted_coverage} tone="green"/><Score label="AI-like writing signal" value={result.summary.ai_likelihood} tone="slate" note={result.ai_detection.label}/></div>
<div className={`status ${result.web_discovery.diagnostics?.api_connected?"ok":"warn"}`}><b>Web search:</b> {result.web_discovery.diagnostics?.api_connected?"Connected":"Not confirmed"} · {result.web_discovery.source_count} candidate source(s)</div><Diagnostics d={result.web_discovery.diagnostics}/>
<div className="tabs">{["overview","document","sources","matches","ai","queries"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
{tab==="overview"&&<><h3>Top attributed sources</h3><Sources rows={result.plagiarism.sources.slice(0,6)}/></>}
{tab==="document"&&<><h3>Highlighted document</h3><DocumentView rows={result.plagiarism.document_sentences}/></>}
{tab==="sources"&&<><h3>Attributed sources</h3><Sources rows={result.plagiarism.sources}/></>}
{tab==="matches"&&<><h3>Matched passages</h3><div className="matches">{result.plagiarism.matches?.length?result.plagiarism.matches.slice(0,30).map((m,i)=><div className={`match ${m.classification}`} key={i}><div><b>{labels[m.classification]}</b><strong>{m.similarity}%</strong></div><p><b>Your text:</b> {m.sentence}</p><p><b>Source text/window:</b> {m.matched_text}</p><div className="signal-row"><span>TF-IDF {m.signals?.tfidf}%</span><span>Sequence {m.signals?.sequence}%</span><span>4-gram {m.signals?.["4gram"]}%</span><span>5-gram {m.signals?.["5gram"]}%</span><span>6-gram {m.signals?.["6gram"]}%</span></div><a href={m.source?.startsWith("http")?m.source:undefined} target="_blank" rel="noreferrer">{m.source_title}</a></div>):<div className="empty">No high-confidence passage overlaps were found.</div>}</div></>}
{tab==="ai"&&<><div className="aisummary"><b>{result.ai_detection.label}</b><span>Confidence: {result.ai_detection.confidence}</span><p>{result.ai_detection.warning}</p></div><div className="signals">{result.ai_detection.signals?.map(s=><div className="signal" key={s.name}><div><b>{s.name}</b><p>{s.explanation}</p></div><strong>{s.value}%</strong></div>)}</div></>}
{tab==="queries"&&<><h3>Search diagnostics</h3><div className="query-list">{result.web_discovery.queries?.length?result.web_discovery.queries.map((q,i)=><div className="query" key={i}><div><b>{q.stage}</b><span>HTTP {q.status}</span><span>{q.results} result(s)</span></div><code>{q.query}</code></div>):<div className="empty">No web queries were executed.</div>}</div></>}
<div className="notes"><b>Review notes</b><ul>{result.limitations.map(x=><li key={x}>{x}</li>)}</ul></div></motion.div>}</div></section></main></div>}
